(function() {var implementors = {};
implementors['serde'] = ["impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rustc_unicode/char/struct.DecodeUtf16Error.html' title='rustc_unicode::char::DecodeUtf16Error'>DecodeUtf16Error</a>","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='serde/bytes/struct.ByteBuf.html' title='serde::bytes::ByteBuf'>ByteBuf</a>","impl&lt;'a&gt; <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='serde/bytes/struct.Bytes.html' title='serde::bytes::Bytes'>Bytes</a>&lt;'a&gt;","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde/de/value/enum.Error.html' title='serde::de::value::Error'>Error</a>","impl <a class='trait' href='core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde/de/enum.Type.html' title='serde::de::Type'>Type</a>",];implementors['serde_cbor'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde_cbor/error/enum.Error.html' title='serde_cbor::error::Error'>Error</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde_cbor/value/enum.Value.html' title='serde_cbor::value::Value'>Value</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='serde_cbor/value/enum.ObjectKey.html' title='serde_cbor::value::ObjectKey'>ObjectKey</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
